data:
  name: '2Dplanar'
  datapath: '/home/vdtrung/trungvd/data/physics_informed/2Dplanar/planestrain_bodyforce_257_rng0.mat'
  total_num: 1000
  offset: 0
  n_sample: 1000
  nx: 257
  sub: 4
  pde_sub: 2
  E: 1.33333333
  nu: 0.33333333

model:
  in_dim: 4
  out_dim: 5
  layers: [32, 32, 32, 32, 32]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu

train:
  batchsize: 20
  epochs: 1000
  milestones: [100, 200, 300, 400, 500, 600, 700, 800, 900]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: '2D-planar'
  save_name: '2Dplanar-pretrain.pt'
  loss_save_name: 'train_loss_history.txt'

log:
  project: 'PINO-2Dplanar-pretrain'
