data:
  name: 'Euler-Bernoulli Beam'
  datapath: '/home/vdtrung/machine_learning/GItHub/data/physics_informed/eb_beam_linear_1025.mat'
  total_num: 5000
  offset: 0
  n_sample: 1000
  nx: 1025
  sub: 8
  q0: -1.0
  EI: 1.0
  L: 1.0

model:
  layers: [64, 64, 64, 64, 64]
  modes: [10, 10, 10, 10]
  fc_dim: 128
  act: gelu

train:
  batchsize: 20
  epochs: 1000
  milestones: [ 100, 200, 300, 400, 500, 600, 700, 800, 900 ]
  base_lr: 0.001
  scheduler_gamma: 0.5
  bc_loss_l: 0.0
  bc_loss_r: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  balance_scheme: 'sum'
  save_dir: 'eb-beam'
  save_name: 'eb-beam-pretrain-eqn.pt'
  loss_save_name: 'train_loss_history.txt'