data:
  name: 'Elastic-Bar'
  datapath: '/home/vdtrung/machine_learning/GItHub/data/physics_informed/elastic_bar_nonlinear_spline_1025.mat'
  total_num: 5000
  offset: 0
  n_sample: 1000
  nx: 1025
  sub: 8
  in_dim: 2
  out_dim: 2
  A0: 1.0
  P0: 1.0
  E: 1.0
  L: 1.0

model:
  name: 'fno'
  layers: [64, 64, 64, 64, 64]
  modes: [10, 10, 10, 10]
  fc_dim: 128
  act: gelu
  apply_output_transform: 'yes'

train:
  batchsize: 20
  epochs: 200
  milestones: [ 100, 200, 300, 400, 500, 600, 700, 800, 900 ]
  base_lr: 0.001
  scheduler_gamma: 0.5
  f_loss: 1.0
  bc_loss_l: 0.0
  bc_loss_r: 0.0
  xy_loss: 0.0
  pino_loss: 'reduced_order'
  balance_scheme: 'sum'
  save_dir: 'elastic-bar'
  save_name: 'elastic-bar-pretrain-eqn.pt'
  loss_save_name: 'train_loss_history.txt'